name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: |
        npm run build
    - name: Release
      run: |
        git config user.name GitHub Actions
        git config user.email actions@github.com
        npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}